language: node_js
node_js:
  - stable

before_install:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN

install:
  - npm install -g codecov
  - npm install

branches:
  only:
    - /.*/

script:
  - npm run lint
  - npm test
  - npm run report-coverage
  - codecov